MvcTrabajoMaster/Controllers/JugadoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTrabajoMaster.Filters;
using MvcTrabajoMaster.Models;
using MvcTrabajoMaster.Services;
using NuggetModelsPryectoJalt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MvcTrabajoMaster.Controllers
{
    public class JugadoresController : Controller
    {
        private ServiceApiTorneos service;

        public JugadoresController(ServiceApiTorneos service)
        {
            this.service = service;
        }
        public async Task<IActionResult> ListaJugadores()
        {
        
            List<Jugador> Jugadores = await this.service.GetJugadoresAsync();
            return View(Jugadores);
        }

        public async Task<IActionResult> ListaJugadoresAdmin(int? posicion)
        {
            List<Jugador> Jugadores = await this.service.GetJugadoresAsync();
            return View(Jugadores);
        }

        public async Task<IActionResult> PerfilJugador(int idjugador)
        {
            List<VistaTorneoJugador> TorneosJugador = await this.service.GetTorneosByIdJugadorAsync(idjugador);
            List<VistaSetFormateado> Sets = await this.service.GetSetsFormatByIdJugadorAsync(idjugador);
            Jugador jug = await this.service.GetJugadorByIdAsync(idjugador);
            ViewData["SETS"] = Sets;
            ViewData["TORNEOS"] = TorneosJugador;
            int setganados = 0;
            foreach (VistaSetFormateado set in Sets)
            {
                if (set.NickGanador == jug.Nick)
                {
                    setganados += 1;
                }
            }
            ViewData["SETS"] = Sets;
            ViewData["TORNEOS"] = TorneosJugador;
            ViewData["SETSGANADOS"] = setganados;
            ViewData["NUMSETS"] = Sets.Count();
            double winrate = ((double)setganados / (double)Sets.Count()) * 100;

            ViewData["WINRATE"] = winrate;
            return View(jug);
        }

        [AuthorizeJugadores]
        public async Task<IActionResult> MiPerfil()
        {
            int idjugador = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            List<VistaTorneoJugador> TorneosJugador = await this.service.GetTorneosByIdJugadorAsync(idjugador);
            List<VistaSetFormateado> Sets = await this.service.GetSetsFormatByIdJugadorAsync(idjugador);

            Jugador jug = await this.service.GetJugadorByIdAsync(idjugador);
            int setganados = 0;
            foreach (VistaSetFormateado set in Sets)
            {
                if (set.NickGanador == jug.Nick)
                {
                    setganados += 1;
                }
            }
            ViewData["SETS"] = Sets;
            ViewData["TORNEOS"] = TorneosJugador;
            ViewData["SETSGANADOS"] = setganados;
            ViewData["NUMSETS"] = Sets.Count();
            double winrate = ((double)setganados / (double)Sets.Count()) * 100;

            ViewData["WINRATE"] = winrate;
            return View(jug);
        }

        public IActionResult NuevoJugador()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> NuevoJugador(string nick,
            string region, string nombre, string email, string password,
            string rol, string equipo)
        {
            int idjugMax = await this.service.GetJugadorMaxIdAsync();

            Jugador jug = new Jugador()
            {
                IdJugador = idjugMax,
                Nick = nick,
                Region = region,
                Nombre = nombre,
                Email = email,
                Password = password,
                Rol = rol,
                Equipo = equipo
            };
            await this.service.InsertJugadorAsync(jug);
            return RedirectToAction("MiPerfil");
        }

        public async Task<IActionResult> EliminarJugador(int idjugador)
        {
            await this.service.DeleteJugadorAsync(idjugador);
            return RedirectToAction("ListaJugadoresAdmin");
        }
        public async Task<IActionResult> EditarJugador(int idjugador)
        {
            Jugador jugadorEditar = await this.service.GetJugadorByIdAsync(idjugador);
            return View(jugadorEditar);
        }

        [HttpPost]
        public async Task<IActionResult> EditarJugador(int idjugador,
            string nick, string region, string nombre,
            string email, string rol, string equipo)
        {

            Jugador jug = new Jugador()
            {
                IdJugador = idjugador,
                Nick = nick,
                Region = region,
                Nombre = nombre,
                Email = email,               
                Rol = rol,
                Equipo = equipo
            };

            await this.service.UpdateJugadorAsync(jug);
            return RedirectToAction("ListaJugadores");
        }
    }
}

MvcTrabajoMaster/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcTrabajoMaster.Services;
using NuggetModelsPryectoJalt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MvcTrabajoMaster.Controllers
{
    public class ManagedController : Controller
    {
        private ServiceApiTorneos service;

        public ManagedController(ServiceApiTorneos service)
        {
            this.service = service;
        }
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogIn(string username, string password)
        {
            string token =
            await this.service.GetTokenAsync(username, password);
            if (token == null)
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
            else
            {
                //SI EL USUARIO EXISTE, ALMACENAMOS EL TOKEN EN SESSION
                Jugador usu = await this.service.GetPerfilUsuario(token);
                ClaimsIdentity identity =
                new ClaimsIdentity
                (CookieAuthenticationDefaults.AuthenticationScheme
                , ClaimTypes.Name, ClaimTypes.NameIdentifier);
                identity.AddClaim(new Claim(ClaimTypes.Name, usu.Nick.ToString()));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, usu.IdJugador.ToString()));
                identity.AddClaim(new Claim(ClaimTypes.Role, usu.Rol.ToString()));
                identity.AddClaim(new Claim("TOKEN", token));
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync
                (CookieAuthenticationDefaults.AuthenticationScheme
                , principal, new AuthenticationProperties
                {
                    IsPersistent = true,
                    ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
                });
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync
            (CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcTrabajoMaster/Controllers/TorneosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcTrabajoMaster.Filters;
using MvcTrabajoMaster.Services;
using NuggetModelsPryectoJalt;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MvcTrabajoMaster.Controllers
{
    public class TorneosController : Controller
    {

        private ServiceApiTorneos service;
 
        private ServiceStorageS3 serviceS3;
        public TorneosController(ServiceApiTorneos service, ServiceStorageS3 serviceS3)
        {
            this.service = service;
            this.serviceS3 = serviceS3;
        }
        [AuthorizeJugadores]
        public async Task<IActionResult> ListaTorneos(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            int MaxRegistro = await this.service.GetNumeroTorneosAsync();
            ViewData["REGISTROS"] = MaxRegistro;
            int siguiente = posicion.Value + 1;
            if (siguiente > MaxRegistro)
            {
                siguiente = MaxRegistro;
                ViewData["MENSAJE"] = "Este es el ultimo torneo";
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
                ViewData["MENSAJE"] = "Este es el primer primer torneo";
            }
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;

            List<VistaTorneo> torneos = await this.service.GetTorneosPaginadoAsync(posicion.Value);
            return View(torneos);
        }

        public async Task<IActionResult> ListaTorneosAdmin(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            int MaxRegistro = await this.service.GetNumeroTorneosAsync();
            ViewData["REGISTROS"] = MaxRegistro;
            int siguiente = posicion.Value + 1;
            if (siguiente > MaxRegistro)
            {
                siguiente = MaxRegistro;
                ViewData["MENSAJE"] = "Este es el ultimo torneo";
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
                ViewData["MENSAJE"] = "Este es el primer primer torneo";
            }
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;
            List<VistaTorneo> torneos = await this.service.GetTorneosPaginadoAsync(posicion.Value);
            return View(torneos);
        }
        public async Task<IActionResult> DetallesTorneo(int idtorneo)
        {
            List<VistaApuntadosTorneo> apuntados = await this.service.GetVApuntadosByTorneoNoPagAsync(idtorneo);
            Torneo torneo = await this.service.GetTorneoByIdAsync(idtorneo);
            ViewData["TORNEO"] = torneo;
            return View(apuntados);
        }

        public IActionResult NuevoTorneo()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> NuevoTorneo(string nombre, string region,
            DateTime fecha, int napuntados, string descripcion,
            string normas, string tipo, string link, IFormFile foto)
        {
            int idtorneoMax = await this.service.GetTorneoMaxIdAsync()+1;


           
            string nombreFile = foto.FileName;
            using (Stream stream = foto.OpenReadStream())
            {
                await this.serviceS3.UploadFileAsync(stream, nombreFile);
            }
            Torneo torneo = new Torneo()
            {
                IdTorneo = idtorneoMax,
                Nombre = nombre,
                Region = region,
                Fecha = fecha, 
                Napuntados = napuntados,
                Descripcion = descripcion,
                Normas = normas,
                Tipo = tipo,
                Link = link,
                Foto = nombreFile
            };

           await this.service.InsertTorneoAsync(torneo);
            return RedirectToAction("ListaTorneos");
        }
    

        public async Task<IActionResult> EliminarTorneo(int idtorneo)
        {
             await this.service.DeleteTorneo(idtorneo);
             return RedirectToAction("ListaTorneosAdmin");
        }

        public async Task<IActionResult> EditarTorneo(int idtorneo)
        {
            Torneo torneo = await this.service.GetTorneoByIdAsync(idtorneo);
            return View(torneo);
        }

        [HttpPost]
        public async Task<IActionResult> EditarTorneo(int idtorneo, string nombre,
            string region, DateTime fecha, int napuntados,
            string descripcion, string normas, string tipo,
            string link, IFormFile foto)
       {


            string nombreFile = foto.FileName;
            using (Stream stream = foto.OpenReadStream())
            {
                await this.serviceS3.UploadFileAsync(stream, nombreFile);
            }
            Torneo torneo = new Torneo()
            {
                IdTorneo = idtorneo,
                Nombre = nombre,
                Region = region,
                Fecha = fecha,
                Napuntados = napuntados,
                Descripcion = descripcion,
                Normas = normas,
                Tipo = tipo,
                Link = link,
                Foto = nombreFile
            };
            await this.service.UpdateTorneoAsync(torneo);

            return RedirectToAction("ListaTorneos");
        }


    }
}

MvcTrabajoMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcTrabajoMaster</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand mx-5" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://bucketproyectojalt.s3.amazonaws.com/logo.png" height="50" width="50"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item mx-5">
                            <a class="nav-link text-dark mx-3" asp-area=""
                               asp-controller="Torneos"
                               asp-action="ListaTorneos">
                                <img src="https://bucketproyectojalt.s3.amazonaws.com/logotorneos-removebg-preview.png" height="75" width="75" />
                            </a>
                        </li>
                        <li class="nav-item mx-5">
                            <a class="nav-link text-dark mx-3" asp-area=""
                               asp-controller="Jugadores"
                               asp-action="ListaJugadores">
                                <img src="https://bucketproyectojalt.s3.amazonaws.com/playerslogo-removebg-preview.png" height="75" width="120" />
                            </a>
                        </li>
                        <li class="nav-item mx-5">
                            <a class="nav-link text-dark mx-3" asp-area=""
                               asp-controller="Jugadores"
                               asp-action="MiPerfil">
                                <img src="https://bucketproyectojalt.s3.amazonaws.com/profile-removebg-preview.png" height="75" width="95" />
                            </a>
                        </li>
                        @if (Context.User.Identity.IsAuthenticated == true)
                        {
                            @if (Context.User.FindFirst(ClaimTypes.Role).Value == "Admin")
                            {
                                <li class="nav-item mx-5">
                                    <a asp-controller="Home"
                                       asp-action="VistaAdmin">
                                        <img src="https://bucketproyectojalt.s3.amazonaws.com/admin-removebg-preview.png" height="75" width="75" />

                                    </a>
                                </li>
                            }                      
                        }
                        @if (Context.User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item mx-5">
                                <a class="nav-link text-dark mx-3" asp-area=""
                                   asp-controller="Managed"
                                   asp-action="LogOut">
                                    <img src="https://bucketproyectojalt.s3.amazonaws.com/logout-removebg-preview.png" height="75" width="95" />
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcTrabajoMaster - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>