MvcTrabajoMaster/Controllers/ApuntadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTrabajoMaster.Filters;
using MvcTrabajoMaster.Services;
using NuggetModelsPryectoJalt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcTrabajoMaster.Controllers
{
    public class ApuntadosController : Controller
    {

        private ServiceApiTorneos service;

        public ApuntadosController(ServiceApiTorneos service)
        {
            this.service = service;
        }
        public async Task<IActionResult> ListaApuntadosTorneo(int idtorneo, int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }

            ViewData["IDTORNEO"] = idtorneo;
            int Napuntados = await this.service.GetNApuntadosTorneoAsync(idtorneo);
            ViewData["NAPUNTADOS"] = Napuntados;
            int siguiente = posicion.Value + 20;
            int anterior = posicion.Value - 20;
            if (siguiente >= Napuntados)
            {
                siguiente = Napuntados;
            }
            if (anterior < 1)
            {
                anterior = 1;
            }

            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;
            List<VistaApuntadosTorneo> apuntados = 
                await this.service.GetVApuntadosByTorneoNoPagAsync(idtorneo);

            return View(apuntados);

        }
        public async Task<IActionResult> ListaApuntadosAdmin(int? idtorneo)
        {

            if (idtorneo == null)
            {
                List<VistaApuntadosTorneo> apuntados = await this.service.GetVApuntadosAsync();
                return View(apuntados);
            }
            else
            {
                List<VistaApuntadosTorneo> apuntadostor = await this.service.GetVApuntadosByTorneoNoPagAsync(idtorneo.Value);
                return View(apuntadostor);
            }
        }
    
        [AuthorizeJugadores]
        public async Task<IActionResult> NuevoApuntado(int idtorneo)
        {
            Torneo torneo = await this.service.GetTorneoByIdAsync(idtorneo);
            return View(torneo);
        }

        [HttpPost]
        public async Task<IActionResult> NuevoApuntado(
            int idtorneo, int idjugador, int puesto,
            string record, int seed)
        {
            int idapMax = await this.service.GetApuntadoMaxIdAsync();
            Apuntado ap = new Apuntado()
            {
                IdApuntado = idapMax,
                IdTorneo = idtorneo,
                IdJugador = idjugador,
                Puesto = puesto,
                Record = record,
                Seed = seed
            };
            string token = HttpContext.User.FindFirst("TOKEN").Value;
            await this.service.InsertApuntadoAsync(ap, token);
            await this.service.SumarApuntadoAsync(idtorneo);
            return RedirectToAction("ListaApuntadosTorneo",
                new { idtorneo }
                );
        }
        public async Task<IActionResult> EditarApuntado(int idapuntado)
        {
            Apuntado apuntadoEditar = await this.service.GetApuntadoByIdAsync(idapuntado);
            return View(apuntadoEditar);
        }

        [HttpPost]
        public async Task<IActionResult> EditarApuntado(int idinscripcion,
            int idtorneo, int idjugador, int puesto,
            string record, int seed)
        {
            Apuntado ap = new Apuntado()
            {
                IdApuntado = idinscripcion,
                IdTorneo = idtorneo,
                IdJugador = idjugador,
                Puesto = puesto,
                Record = record,
                Seed = seed
            };
            await this.service.UpdateApuntadoAsync(ap);
            return RedirectToAction("ListaApuntadosAdmin");
        }

        public async Task<IActionResult> EliminarApuntado(int idapuntado)
        {
            await this.service.DeleteApuntadoAsync(idapuntado);
            return RedirectToAction("ListaTorneosAdmin", controllerName: "Torneos");
        }
    }
}

MvcTrabajoMaster/Controllers/JugadoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTrabajoMaster.Filters;
using MvcTrabajoMaster.Models;
using MvcTrabajoMaster.Services;
using NuggetModelsPryectoJalt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MvcTrabajoMaster.Controllers
{
    public class JugadoresController : Controller
    {
        private ServiceApiTorneos service;

        public JugadoresController(ServiceApiTorneos service)
        {
            this.service = service;
        }
        public async Task<IActionResult> ListaJugadores()
        {
        
            List<Jugador> Jugadores = await this.service.GetJugadoresAsync();
            return View(Jugadores);
        }

        public async Task<IActionResult> ListaJugadoresAdmin(int? posicion)
        {
            List<Jugador> Jugadores = await this.service.GetJugadoresAsync();
            return View(Jugadores);
        }

        public async Task<IActionResult> PerfilJugador(int idjugador)
        {
            List<VistaTorneoJugador> TorneosJugador = await this.service.GetTorneosByIdJugadorAsync(idjugador);
            List<VistaSetFormateado> Sets = await this.service.GetSetsFormatByIdJugadorAsync(idjugador);
            Jugador jug = await this.service.GetJugadorByIdAsync(idjugador);
            ViewData["SETS"] = Sets;
            ViewData["TORNEOS"] = TorneosJugador;
            int setganados = 0;
            foreach (VistaSetFormateado set in Sets)
            {
                if (set.NickGanador == jug.Nick)
                {
                    setganados += 1;
                }
            }
            ViewData["SETS"] = Sets;
            ViewData["TORNEOS"] = TorneosJugador;
            ViewData["SETSGANADOS"] = setganados;
            ViewData["NUMSETS"] = Sets.Count();
            double winrate = ((double)setganados / (double)Sets.Count()) * 100;

            ViewData["WINRATE"] = winrate;
            return View(jug);
        }

        [AuthorizeJugadores]
        public async Task<IActionResult> MiPerfil()
        {
            int idjugador = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            List<VistaTorneoJugador> TorneosJugador = await this.service.GetTorneosByIdJugadorAsync(idjugador);
            List<VistaSetFormateado> Sets = await this.service.GetSetsFormatByIdJugadorAsync(idjugador);

            Jugador jug = await this.service.GetJugadorByIdAsync(idjugador);
            int setganados = 0;
            foreach (VistaSetFormateado set in Sets)
            {
                if (set.NickGanador == jug.Nick)
                {
                    setganados += 1;
                }
            }
            ViewData["SETS"] = Sets;
            ViewData["TORNEOS"] = TorneosJugador;
            ViewData["SETSGANADOS"] = setganados;
            ViewData["NUMSETS"] = Sets.Count();
            double winrate = ((double)setganados / (double)Sets.Count()) * 100;

            ViewData["WINRATE"] = winrate;
            return View(jug);
        }

        public IActionResult NuevoJugador()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> NuevoJugador(string nick,
            string region, string nombre, string email, string password,
            string rol, string equipo)
        {
            int idjugMax = await this.service.GetJugadorMaxIdAsync();

            Jugador jug = new Jugador()
            {
                IdJugador = idjugMax,
                Nick = nick,
                Region = region,
                Nombre = nombre,
                Email = email,
                Password = password,
                Rol = rol,
                Equipo = equipo
            };
            await this.service.InsertJugadorAsync(jug);
            return RedirectToAction("MiPerfil");
        }

        public async Task<IActionResult> EliminarJugador(int idjugador)
        {
            await this.service.DeleteJugadorAsync(idjugador);
            return RedirectToAction("ListaJugadoresAdmin");
        }
        public async Task<IActionResult> EditarJugador(int idjugador)
        {
            Jugador jugadorEditar = await this.service.GetJugadorByIdAsync(idjugador);
            return View(jugadorEditar);
        }

        [HttpPost]
        public async Task<IActionResult> EditarJugador(int idjugador,
            string nick, string region, string nombre,
            string email, string rol, string equipo)
        {

            Jugador jug = new Jugador()
            {
                IdJugador = idjugador,
                Nick = nick,
                Region = region,
                Nombre = nombre,
                Email = email,               
                Rol = rol,
                Equipo = equipo
            };

            await this.service.UpdateJugadorAsync(jug);
            return RedirectToAction("ListaJugadores");
        }
    }
}

MvcTrabajoMaster/Controllers/SetsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTrabajoMaster.Services;
using NuggetModelsPryectoJalt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcTrabajoMaster.Controllers
{
    public class SetsController : Controller
    {
        private ServiceApiTorneos service;

        public SetsController(ServiceApiTorneos service)
        {
            this.service = service;          
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> EditarSet(int idset, int idtorneo)
        {
            Set setEditar = await this.service.GetSetByIdAsync(idset);
            List<VistaApuntadosTorneo> apuntados = await this.service.GetVApuntadosByTorneoNoPagAsync(idtorneo);
            ViewData["RONDA"] = setEditar.Ronda;
            ViewData["RESULTADO"] = setEditar.Resultado;
            ViewData["IDTORNEO"] = idtorneo;
            return View(apuntados);
        }
        [HttpPost]
        public async Task<IActionResult> EditarSet(int idset, int ap1,
            int ap2, int apganador, string resultado,
            string ronda, int idtorneo)
        {
            Set set = new Set()
            {
                IdSet = idset,
                IdApuntado1 = ap1,
                IdApuntado2 = ap2,
                Ganador = apganador,
                Resultado = resultado,
                Ronda = ronda,
                IdTorneo = idtorneo
            };
            await this.service.UpdateSetAsync(set);
            return RedirectToAction("ListaSetsApuntadoAdmin",
                new { idap = apganador }
               );
        }

        public async Task<IActionResult> NuevoSet(int idtorneo)
        {
            ViewData["IDTORNEO"] = idtorneo;
            List<VistaApuntadosTorneo> apuntados = await this.service.GetVApuntadosByTorneoNoPagAsync(idtorneo);
            return View(apuntados);
        }

        [HttpPost]
        public async Task<IActionResult> NuevoSet(int ap1, int ap2,
            int apganador, string resultado, string ronda,
            int idtorneo)
        {
            int idsetMax = await this.service.GetSetMaxIdAsync();
            Set set = new Set()
            {
                IdSet = idsetMax,
                IdApuntado1 = ap1,
                IdApuntado2 = ap2,
                Ganador = apganador,
                Resultado = resultado,
                Ronda = ronda,
                IdTorneo = idtorneo
            };
            return RedirectToAction("ListaSetsApuntado",
                 new { idap = apganador }
                );
        }

        public async Task<IActionResult> ListaSetsApuntado(int idap)
        {
            List<VistaSetFormateado> vistaSets = await this.service.GetSetsFormatByIdApuntadoAsync(idap);
            return View(vistaSets);
        }
        public async Task<IActionResult> ListaSetsApuntadoAdmin(int idap)
        {
            List<VistaSetFormateado> vistaSets = await this.service.GetSetsFormatByIdApuntadoAsync(idap);
            return View(vistaSets);
        }
    }
}

MvcTrabajoMaster/Views/Apuntados/EditarApuntado.cshtml
@model Apuntado
<h1>Editar Apuntado</h1>
<form method="post" class="form-group align-content-center">
    <input type="hidden" name="idinscripcion" value="@Model.IdApuntado" />
    <input type="hidden" name="idtorneo" class="form-control" value="@Model.IdTorneo" />
    <input type="hidden" name="idjugador" class="form-control" value="@Model.IdJugador" />

    <div class="input-group my-2">
        <label class="input-group-text">Puesto: </label>
        <input type="number" name="puesto" class="form-control" value="@Model.Puesto" />
    </div>
    <div class="input-group my-2">
        <label class="input-group-text">Record: </label>
        <input type="text" name="record" class="form-control" value="@Model.Record" />
    </div>

    <div class="input-group my-2">
        <label class="input-group-text">Seed: </label>
        <input type="text" name="seed" class="form-control" value="@Model.Seed" />
    </div>
    <button type="submit" class="btn btn-outline-info form-control">
        Enviar
    </button>
</form>

MvcTrabajoMaster/Views/Apuntados/ListaApuntadosAdmin.cshtml
@model List<VistaApuntadosTorneo>
<div class="container">
    <h1 class="text-center">
        Lista apuntados admin
    </h1>
    <div class="row text-center">
        <a asp-controller="Home"
           asp-action="VistaAdmin"
           class="btn btn-danger form-control">
            Volver
        </a>
    </div>

    @{
        int num = 0;
        double winrate = 0;
    }
    @foreach (VistaApuntadosTorneo vista in @Model)
    {
        @if (num % 2 == 0)
        {

            <div class="container">
                <div class="row" style="background-color: lightsalmon">


                    <div class="col my-3">
                        @if (vista.Equipo != null)
                        {
                            <span style="color:dimgrey">@vista.Equipo | </span>
                        }

                        <span>@vista.Nick</span>
                    </div>
                    <div class="col my-3">
                        Puesto: @vista.Puesto
                    </div>
                    <div class="col my-3">
                        Record: @vista.Record
                    </div>
                    <div class="col my-3">
                        Seed: @vista.Seed
                    </div>
                    <div class="col my-3">
                        Torneo: @vista.IdTorneo
                    </div>
                    <div class="col">

                        <a asp-controller="Apuntados"
                           asp-action="EliminarApuntado"
                           asp-route-idapuntado="@vista.IdApuntado"
                           class="btn btn-secondary" style="width: 5em; height:2em">
                            Eliminar
                        </a>

                        <a asp-controller="Apuntados"
                           asp-action="EditarApuntado"
                           asp-route-idapuntado="@vista.IdApuntado"
                           class="btn btn-secondary" style="width: 5em; height:2em">
                            Editar
                        </a>
                        <a asp-controller="Sets"
                           asp-action="ListaSetsApuntadoAdmin"
                           asp-route-idap="@vista.IdApuntado"
                           class="btn btn-secondary" style="width: 5em; height:2em">
                            Sets
                        </a>
                    </div>




                </div>
            </div>

        }
        else
        {
            <div class="container">
                <div class="row " style="background-color: lightblue">


                    <div class="col my-3">
                        @if (vista.Equipo != null)
                        {
                            <span style="color:dimgrey">@vista.Equipo | </span>
                        }

                        <span>@vista.Nick</span>
                    </div>
                    <div class="col my-3">
                        Puesto: @vista.Puesto
                    </div>
                    <div class="col my-3">
                        Record: @vista.Record
                    </div>
                    <div class="col my-3">
                        Seed: @vista.Seed
                    </div>
                    <div class="col my-3">
                        Torneo: @vista.IdTorneo
                    </div>
                    <div class="col">


                        <a asp-controller="Apuntados"
                           asp-action="EliminarApuntado"
                           asp-route-idapuntado="@vista.IdApuntado"
                           class="btn btn-warning" style="width: 5em; height:2em">
                            Eliminar
                        </a>

                        <a asp-controller="Apuntados"
                           asp-action="EditarApuntado"
                           asp-route-idapuntado="@vista.IdApuntado"
                           class="btn btn-warning" style="width: 5em; height:2em">
                            Editar
                        </a>
                        <a asp-controller="Sets"
                           asp-action="ListaSetsApuntadoAdmin"
                           asp-route-idapuntado="@vista.IdApuntado"
                           class="btn btn-warning" style="width: 5em; height:2em">
                            Sets
                        </a>
                    </div>

                </div>
            </div>

        }
        {
            num += 1;
        }
    }

</div>

MvcTrabajoMaster/Views/Apuntados/ListaApuntadosTorneo.cshtml
@model List<VistaApuntadosTorneo>
<div class="container">
    <h1 class="text-center">
        Lista apuntados torneos
    </h1>
   
    @{
        int num = 0;
        double winrate = 0;
    }
    @foreach (VistaApuntadosTorneo vista in @Model)
    {
        {
            if (vista.Record != "0")
            {
                char[] record;
                record = vista.Record.ToCharArray();
                string stringwins = record[0].ToString();
                string stringloses = record[2].ToString();
                double wins = Double.Parse(stringwins);
                double loses = Double.Parse(stringloses);
                double games = wins + loses;
                winrate = (wins / games) * 100;
                winrate = (Math.Round(winrate, 0));
            }

        }
        @if (num % 2 == 0)
        {

            <div class="container">
                <div class="row" style="background-color: lightsalmon">


                    <div class="col my-3">
                        @if (vista.Equipo != null)
                        {
                            <span style="color:dimgrey">@vista.Equipo | </span>
                        }

                        <span>@vista.Nick</span>
                    </div>
                    <div class="col my-3">
                        Puesto: @vista.Puesto
                    </div>
                    <div class="col my-3">
                        Record: @vista.Record
                    </div>
                    <div class="col my-3">
                        Seed: @vista.Seed
                    </div>
                    <div class="col my-3">
                        WinRate = @winrate%
                    </div>
                    <div class="col">

                        <a asp-controller="Sets"
                           asp-action="ListaSetsApuntado"
                           asp-route-idap="@vista.IdApuntado"
                           class="btn btn-secondary" style="width: 5em; height:2em">
                            Sets
                        </a>

                        <a asp-controller="Jugadores"
                           asp-action="PerfilJugador"
                           asp-route-idjugador="@vista.IdJugador"
                           class="btn btn-secondary" style="width: 5em; height:2em">
                            Perfil
                        </a>

                    </div>




                </div>
            </div>

        }
        else
        {
            <div class="container">
                <div class="row " style="background-color: lightblue">


                    <div class="col my-3">
                        @if (vista.Equipo != null)
                        {
                            <span style="color:dimgrey">@vista.Equipo | </span>
                        }

                        <span>@vista.Nick</span>
                    </div>
                    <div class="col my-3">
                        Puesto: @vista.Puesto
                    </div>
                    <div class="col my-3">
                        Record: @vista.Record
                    </div>
                    <div class="col my-3">
                        Seed: @vista.Seed
                    </div>
                    <div class="col my-3">
                        WinRate = @winrate%
                    </div>
                    <div class="col">

                        <a asp-controller="Sets"
                           asp-action="ListaSetsApuntado"
                           asp-route-idap="@vista.IdApuntado"
                           class="btn btn-warning" style="width: 5em; height:2em">
                            Sets
                        </a>

                        <a asp-controller="Jugadores"
                           asp-action="PerfilJugador"
                           asp-route-idjugador="@vista.IdJugador"
                           class="btn btn-warning" style="width: 5em; height:2em">
                            Perfil
                        </a>

                    </div>

                </div>
            </div>

        }
        {
            num += 1;
        }
    }

</div>

MvcTrabajoMaster/Views/Apuntados/NuevoApuntado.cshtml
@model Torneo
@{
    int idjugador = int.Parse(Context.User.FindFirst(ClaimTypes.NameIdentifier).Value);
}

<form method="post" class="form-group align-content-center">

    <div class="input-group my-2">
        <h1>Apuntarse al torneo: @Model.Nombre</h1>
    </div>
    <div class="input-group my-2">
        <input type="hidden" name="idTorneo" value="@Model.IdTorneo" class="form-control" />
        <input type="hidden" name="idJugador" value="@idjugador" class="form-control" />
        <input type="hidden" name="puesto" value="0" class="form-control" />
        <input type="hidden" name="record" value="0" class="form-control" />
        <input type="hidden" name="set" value="0" class="form-control" />
    </div>

    <button type="submit" class="btn btn-outline-info form-control">
        Confirmar
    </button>
    <a asp-controller="Torneos"
       asp-action="ListaTorneos"
       class="btn btn-danger form-control">
        Volver
    </a>
</form>